global using System.Net.Http.Headers;
global using System.Text.Json;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using parcelfy.Infrastructure.ParcelTrackersRepository;
global using parcelfy.Infrastructure.ParcelTrackersRepository.Abstractions;
global using parcelfy.Infrastructure.ParcelTrackersRepository.Dtos;
global using System.Text.Json.Serialization;