global using System.Diagnostics.CodeAnalysis;
global using System.IdentityModel.Tokens.Jwt;
global using System.Reflection;
global using System.Security.Claims;
global using System.Text;
global using System.Text.Json.Serialization;
global using FluentValidation;
global using FluentValidation.Results;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.OpenApi.Models;
global using parcelfy.Api;
global using parcelfy.Api.Models;
global using parcelfy.Application;
global using parcelfy.Application.ParcelTrackers.Abstractions;
global using parcelfy.Application.ParcelTrackers.Models;
global using parcelfy.Infrastructure;

