name: 👌 Specflow tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  specflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core	
        uses: actions/setup-dotnet@v1	
        with:	
          dotnet-version: '6.0.x'	
          include-prerelease: true
          
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name : Specflow execution 
        uses: actions/cryptic-wizard/run-specflow-tests@v1.3.1
        with:
          test-assembly-path: tests/Bdd/bin/Release/net6.0
          test-assembly-dll: tests/Bdd.dll
          output-html: SpecflowResult.html
          framework: net6.0
          upload-artifact: false
