# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ✍ Unit test coverage - threshold 85%

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3   
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 8.0.x
        include-prerelease: true
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release          

    - name: Create Coverage Directory
      run: mkdir -p coverage
      
    - name: Dotnet Test
      run: |
        dotnet tool install --global dotnet-coverage
        dotnet coverage collect dotnet test --output ./coverage --output-format cobertura        
        # dotnet coverage collect dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      
    - name: Create code coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:coverage/**/coverage.cobertura.xml -targetdir:coverage -reporttypes:'Cobertura;Badges'
  
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/Cobertura.xml
        badge: true
        format: 'markdown'
        output: 'both'
      
    - name: Analyze Test and/or Coverage Results
      uses: runforesight/foresight-test-kit-action@v1
      with:
        api_key: 5f9bf240-a17d-46c9-83a0-33ed1f201e23
        test_format: XUNIT2
        test_framework: XUNIT2
        test_path: <test_results_path_optional>
        coverage_format: COBERTURA/XML
        coverage_path: coverage/Cobertura.xml
        
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
